// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"github.com/google/wire"
	"github.com/tinkler/mqttadmin/pkg/conf"
	"github.com/tinkler/mqttadmin/pkg/db"
	"net/http"
)

// Injectors from wire.go:

func NewServer() (*http.Server, error) {
	confConf := conf.NewConf()
	config := conf.NewGormConfig()
	gormDB, err := db.NewDB(confConf, config)
	if err != nil {
		return nil, err
	}
	server, err := NewRouterServer(confConf, gormDB)
	if err != nil {
		return nil, err
	}
	return server, nil
}

// wire.go:

var (
	confSet = wire.NewSet(conf.NewGormConfig, conf.NewConf)
	dbSet   = wire.NewSet(db.NewDB)
)
