// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route
import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/tinkler/mqttadmin/pkg/jsonz/sjson"
	"github.com/tinkler/ssms/backend/service/store_house/internal/model/sd"
	"github.com/tinkler/mqttadmin/pkg/status"
)

func RoutesSd(m chi.Router) {
	m.Route("/sd", func(r chi.Router) {
		
		r.Post("/goodsview_crud/search-for-goods-view-by-name", func(w http.ResponseWriter, r *http.Request) {
			m := Model[*sd.GoodsviewCRUD, struct{
				Name string 
				 } ]{}
			err := sjson.Bind(r, &m)
			if err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			res := Res[*sd.GoodsviewCRUD,[]*sd.Goodsview]{Data:m.Data}
			res.Resp, err = m.Data.SearchForGoodsViewByName(r.Context(), m.Args.Name, )
			
			if status.HttpError(w, err) {
				return
			}
			if sjson.HttpWrite(w, res) {
				return
			}

		})
	})
}
