// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route

func init() {
	
	routePathMap["/sd/chat/ask-goodsview"] = "internal/model/sd/chat.go:16"
	routePathMap["/sd/goodsview_crud/search-for-goods-view-by-name"] = "internal/model/sd/goods.go:26"
}

