apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvpgsql001
  labels:
    type: hostpath
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/root/k8s/pgsql/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvpgsql
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 5Gi