// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
import { Injectable } from '@angular/core';
import { _HttpClient } from '@delon/theme';

import { Page } from './page.model';
import { User } from './user.model';
import { UserService } from './user.service';

@Injectable({
  providedIn: 'root'
})
export class PageService {
  constructor(private http: _HttpClient, private userSrv: UserService) {}

  newPage(): Page {
    return new Page(this.http);
  }
}
