// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.

import { Injectable } from '@angular/core';
import { _HttpClient } from '@delon/theme';

import { Role } from './role.model';

@Injectable({
  providedIn: 'root'
})
export class RoleService {
  constructor(private http: _HttpClient) {}

  newRole(): Role {
    return new Role(this.http);
  }
}
