apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssms-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssms-auth
  template:
    metadata:
      labels:
        app: ssms-auth
    spec:
      containers:
      - name: ssms-auth
        image: localhost:5000/smss-auth:v0.0.1
        env:
        - name: DB_DSN
          value: "host=192.168.8.12 user=clans password=clans4105 dbname=clans port=5432 sslmode=disable TimeZone=Asia/Shanghai"  # 设置 DSN 环境变量
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "11080"
        - name: SERVER_READ_TIMEOUT
          value: "5"
        - name: SERVER_WRITE_TIMEOUT
          value: "12"
        - name: SERVER_IDLE_TIMEOUT
          value: "120"
        ports:
        - containerPort: 11080
---
apiVersion: v1
kind: Service
metadata:
  name: ssms-auth
spec:
  selector:
    app: ssms-auth
  ports:
  - name: http
    port: 11080
    targetPort: 11080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssms-auth
spec:
  hosts:
  - "*"
  gateways:
  - mqtt-gateway
  http:
  - match:
    - uri:
        prefix: /mqtt
    route:
    - destination:
        host: ssms-auth
        port:
          number: 11080