// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: smart/v1/smart.proto

package smart_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Sender  string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smart_v1_smart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_smart_v1_smart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_smart_v1_smart_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type SmartChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*ChatMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *SmartChat) Reset() {
	*x = SmartChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smart_v1_smart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartChat) ProtoMessage() {}

func (x *SmartChat) ProtoReflect() protoreflect.Message {
	mi := &file_smart_v1_smart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartChat.ProtoReflect.Descriptor instead.
func (*SmartChat) Descriptor() ([]byte, []int) {
	return file_smart_v1_smart_proto_rawDescGZIP(), []int{1}
}

func (x *SmartChat) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SmartHome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentModel string `protobuf:"bytes,1,opt,name=current_model,json=currentModel,proto3" json:"current_model,omitempty"`
}

func (x *SmartHome) Reset() {
	*x = SmartHome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smart_v1_smart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartHome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartHome) ProtoMessage() {}

func (x *SmartHome) ProtoReflect() protoreflect.Message {
	mi := &file_smart_v1_smart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartHome.ProtoReflect.Descriptor instead.
func (*SmartHome) Descriptor() ([]byte, []int) {
	return file_smart_v1_smart_proto_rawDescGZIP(), []int{2}
}

func (x *SmartHome) GetCurrentModel() string {
	if x != nil {
		return x.CurrentModel
	}
	return ""
}

var File_smart_v1_smart_proto protoreflect.FileDescriptor

var file_smart_v1_smart_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2e, 0x76, 0x31,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0b, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x09,
	0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x68, 0x61, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x6d,
	0x61, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x09,
	0x53, 0x6d, 0x61, 0x72, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x32, 0x4f,
	0x0a, 0x09, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x47, 0x73, 0x72, 0x76, 0x12, 0x42, 0x0a, 0x10, 0x53,
	0x6d, 0x61, 0x72, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x45, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x65, 0x12,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x1a, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x73, 0x0a, 0x22, 0x69, 0x6e, 0x6b, 0x2e, 0x73, 0x66, 0x73, 0x2e, 0x74, 0x69, 0x6e, 0x6b, 0x6c,
	0x65, 0x72, 0x2e, 0x6d, 0x71, 0x74, 0x74, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x73, 0x6d, 0x61,
	0x72, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x69, 0x6e, 0x6b, 0x6c, 0x65, 0x72, 0x2f, 0x73, 0x73, 0x6d, 0x73, 0x2f, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x6d, 0x61,
	0x72, 0x74, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x6d, 0x61, 0x72,
	0x74, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smart_v1_smart_proto_rawDescOnce sync.Once
	file_smart_v1_smart_proto_rawDescData = file_smart_v1_smart_proto_rawDesc
)

func file_smart_v1_smart_proto_rawDescGZIP() []byte {
	file_smart_v1_smart_proto_rawDescOnce.Do(func() {
		file_smart_v1_smart_proto_rawDescData = protoimpl.X.CompressGZIP(file_smart_v1_smart_proto_rawDescData)
	})
	return file_smart_v1_smart_proto_rawDescData
}

var file_smart_v1_smart_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_smart_v1_smart_proto_goTypes = []interface{}{
	(*ChatMessage)(nil), // 0: smart.v1.ChatMessage
	(*SmartChat)(nil),   // 1: smart.v1.SmartChat
	(*SmartHome)(nil),   // 2: smart.v1.SmartHome
	(*anypb.Any)(nil),   // 3: google.protobuf.Any
}
var file_smart_v1_smart_proto_depIdxs = []int32{
	0, // 0: smart.v1.SmartChat.messages:type_name -> smart.v1.ChatMessage
	3, // 1: smart.v1.SmartGsrv.SmartHomeEnquire:input_type -> google.protobuf.Any
	3, // 2: smart.v1.SmartGsrv.SmartHomeEnquire:output_type -> google.protobuf.Any
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_smart_v1_smart_proto_init() }
func file_smart_v1_smart_proto_init() {
	if File_smart_v1_smart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smart_v1_smart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smart_v1_smart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smart_v1_smart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartHome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smart_v1_smart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smart_v1_smart_proto_goTypes,
		DependencyIndexes: file_smart_v1_smart_proto_depIdxs,
		MessageInfos:      file_smart_v1_smart_proto_msgTypes,
	}.Build()
	File_smart_v1_smart_proto = out.File
	file_smart_v1_smart_proto_rawDesc = nil
	file_smart_v1_smart_proto_goTypes = nil
	file_smart_v1_smart_proto_depIdxs = nil
}
