// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: smart/v1/smart.proto

package smart_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SmartGsrvClient is the client API for SmartGsrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartGsrvClient interface {
	SmartHomeEnquire(ctx context.Context, opts ...grpc.CallOption) (SmartGsrv_SmartHomeEnquireClient, error)
}

type smartGsrvClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartGsrvClient(cc grpc.ClientConnInterface) SmartGsrvClient {
	return &smartGsrvClient{cc}
}

func (c *smartGsrvClient) SmartHomeEnquire(ctx context.Context, opts ...grpc.CallOption) (SmartGsrv_SmartHomeEnquireClient, error) {
	stream, err := c.cc.NewStream(ctx, &SmartGsrv_ServiceDesc.Streams[0], "/smart.v1.SmartGsrv/SmartHomeEnquire", opts...)
	if err != nil {
		return nil, err
	}
	x := &smartGsrvSmartHomeEnquireClient{stream}
	return x, nil
}

type SmartGsrv_SmartHomeEnquireClient interface {
	Send(*anypb.Any) error
	Recv() (*anypb.Any, error)
	grpc.ClientStream
}

type smartGsrvSmartHomeEnquireClient struct {
	grpc.ClientStream
}

func (x *smartGsrvSmartHomeEnquireClient) Send(m *anypb.Any) error {
	return x.ClientStream.SendMsg(m)
}

func (x *smartGsrvSmartHomeEnquireClient) Recv() (*anypb.Any, error) {
	m := new(anypb.Any)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SmartGsrvServer is the server API for SmartGsrv service.
// All implementations must embed UnimplementedSmartGsrvServer
// for forward compatibility
type SmartGsrvServer interface {
	SmartHomeEnquire(SmartGsrv_SmartHomeEnquireServer) error
	mustEmbedUnimplementedSmartGsrvServer()
}

// UnimplementedSmartGsrvServer must be embedded to have forward compatible implementations.
type UnimplementedSmartGsrvServer struct {
}

func (UnimplementedSmartGsrvServer) SmartHomeEnquire(SmartGsrv_SmartHomeEnquireServer) error {
	return status.Errorf(codes.Unimplemented, "method SmartHomeEnquire not implemented")
}
func (UnimplementedSmartGsrvServer) mustEmbedUnimplementedSmartGsrvServer() {}

// UnsafeSmartGsrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartGsrvServer will
// result in compilation errors.
type UnsafeSmartGsrvServer interface {
	mustEmbedUnimplementedSmartGsrvServer()
}

func RegisterSmartGsrvServer(s grpc.ServiceRegistrar, srv SmartGsrvServer) {
	s.RegisterService(&SmartGsrv_ServiceDesc, srv)
}

func _SmartGsrv_SmartHomeEnquire_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SmartGsrvServer).SmartHomeEnquire(&smartGsrvSmartHomeEnquireServer{stream})
}

type SmartGsrv_SmartHomeEnquireServer interface {
	Send(*anypb.Any) error
	Recv() (*anypb.Any, error)
	grpc.ServerStream
}

type smartGsrvSmartHomeEnquireServer struct {
	grpc.ServerStream
}

func (x *smartGsrvSmartHomeEnquireServer) Send(m *anypb.Any) error {
	return x.ServerStream.SendMsg(m)
}

func (x *smartGsrvSmartHomeEnquireServer) Recv() (*anypb.Any, error) {
	m := new(anypb.Any)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SmartGsrv_ServiceDesc is the grpc.ServiceDesc for SmartGsrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartGsrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smart.v1.SmartGsrv",
	HandlerType: (*SmartGsrvServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SmartHomeEnquire",
			Handler:       _SmartGsrv_SmartHomeEnquire_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "smart/v1/smart.proto",
}
